### ISSUE TITLE
errorlogs doesn't show Logging.exception()

### ISSUE THREAD

**Issue by SomewhatDamaged** [Tobotimus/Tobo-Cogs#57]
As stated. I have errorlogs configured to show all Tracebacks, but when calling the logger and telling it to log an exception, it doesn't show it in channel.

```
        try:
            raise ValueError("blarg")
        except:
            e = sys.exc_info()[0]
            log.exception(e)```

**Comment by Tobotimus** [comment]
I'm afraid not how errorlogs works. It only logs tracebacks of unhandled command errors, i.e. the errors that occur when you see `Error in command "command": check your console or logs for details`. It does not log errors in events because they tend to be very spammy and often users don't care about them. It doesn't log handled errors because that's the responsibility of whoever is handling it.
